apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  namespace: zigbee2mqtt
  labels:
    app: zigbee2mqtt
spec:
  selector:
    matchLabels:
      app: zigbee2mqtt
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      containers:
        - name: zigbee2mqtt
          image: koenkk/zigbee2mqtt:1.40.1
          resources:
            limits:
              akri.sh/akri-zigbee-usb: "1"
            requests:
              akri.sh/akri-zigbee-usb: "1"
          env:
            - name: "ZIGBEE2MQTT_DATA"
              value: "/data"
            - name: "ZIGBEE2MQTT_CONFIG_MQTT_SERVER"
              value: "mqtt://mosquitto.mosquitto.svc.cluster.local"
            - name: "ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC"
              value: "zigbee2mqtt"
            - name: "ZIGBEE2MQTT_CONFIG_PERMIT_JOIN"
              value: "true"
            - name: "ZIGBEE2MQTT_CONFIG_SERIAL_PORT"
              value: "/dev/ttyUSB0"
            - name: "ZIGBEE2MQTT_CONFIG_HOMEASSISTANT"
              value: "true"
            - name: "TZ"
              value: "Europe/Berlin"
          envFrom:
            - secretRef:
                name: zigbee2mqtt-network-key
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: zigbee2mqtt-data
      restartPolicy: Always
