apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zigbee2mqtt-network-key
  namespace: zigbee2mqtt
spec:
  encryptedData:
    ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: AgC/OX09pK4hIwbdVKNMrc3C7dciU2qwc2wOggyOHLPL64jizNJpkd5aQOYAq0roiLkjgfPGMzC8Evshkcb3emJqQsfPOk0JPwys7zJlqvSUxA83t8zMDRFdTW0bMbdw2K6mJcmhjHRuknO2RPe0UsiRIH7cU0zSFalfoFC2MrSxZmAzBJ3HgvkU7TecBJ2E5fyTGSBVy79wuUGiqbQ74HsSfVnAqf/i22yiHJ0PXoA3OhRAEydPbAbnxIMn/Ot+jof5KZ9hSUtoqgB3eH+MDNKw6xu0sNHIUUjzHG6GOhHJlBTIG12PpgZLnyDh/QGOMoB7F0oTKmt/Ms327ThRj0fPwtmiuUQQGsRY0K7mZBMcfBE/hxZ0eU+NNvqww7j9IjDPJcCuWnLraQINwtdD+2HsCcnR4L70LgrabOwfY1Oq64SaadU6bxw3HKnH+YG6kWWqBc4VS7fMGmz/Lzku33px+Yh+saB/+9St+jUVDifZolZEEFr7uEd723CfZgeq2RRNYGFrDplzvoWSJ9rYjmeS3DMvzeyIyYPzQIgzZhJIhTppNDzLES+GBepdK5ccYrU4xbZgoiuEWqs2xaLJpBwKuOFK/FwAG67yHgLquzj+NAQvOjfOnVEzxrQiSLO41pZoBWdNVrV+5ILPY2SZF1CvK9wgOnRLmi+0InoRU+8uHYlJgN/km8wEr+jCxuepSzSkJEskdQag1mmjNwlXlvo9ErvAAcV+P1x33P2RrMCarLb22+4nsjpZ1uwRBcq7ta5kqPxd/PurWBySokXWErzhCdmlNTelNEE=
  template:
    metadata:
      creationTimestamp: null
      name: zigbee2mqtt-network-key
      namespace: zigbee2mqtt
    type: Opaque
