apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zigbee2mqtt-network-key
  namespace: zigbee2mqtt
spec:
  encryptedData:
    ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: AgBVVp9HlgipkbPFkBF80nKHVSlq9tGq6SrVelVoY7IloJVp0MjDQ2OJp/x8tjHwwNvQP+L43SgrdEjUq0zmM+FpFM0dyI1MUO+PhLxpNKavR5XXbn307x9CTR0sYKlyB9Krr0bZErix/p/SFFaSkRCKSgv5wr/ql41jA57qwZKoaCfRddndNVvUcuy7B7cePrICbWi9ZDVbAbHvIpHqQC/yFf1TN3BI6dUe+c7yAhWKYH1/jmtHBtI8n38wbM4xdVDNVJ4UhV7t54mvaf51TFJTLhMV9+l/glJtdzOwn0Ltyywfi1vZlCksy/xUP7s+qChdVh2gDH67JZ22Ktg26oHSyI80b/y8KPwsWVZJ/WzmCKqLUaIgsbcBz4JK7DqQIejulLOWwq4pJqWbDMX4UGlwjtU7/5cZf7YkHCzY9zHrRD6+rQZmab81Kvn2vfYd8TN1ZOMffX7P7b5Iwj8VKT/uuwELw/FdADMYCgDFYmcPNWBVplDYoasEfiIqcUi5o1V7LCj+UPW7Yi5IZbhJrAOT2JfJmVpGB2e7CuzMkl1VmyFnRpu0woBOM2p/m+81+TtgMhUMowSqOw8nb5qU7b+6W6d4VnNH/GwXEY2IaFvTl+pRtgDGFwWOgbMHxJyJjLP25Yc6EraNWRQHwlCDgmnja/aAhbuOUzN/sg+Xx/UlgkQ8C5cCEqIVHwF4e049LhNt+EsgAF4Hn1lY3oJZxH8YcQIKHYTdVUSjtSn0rZLNEH1fVPFRevG8
  template:
    metadata:
      creationTimestamp: null
      name: zigbee2mqtt-network-key
      namespace: zigbee2mqtt
    type: Opaque
